warpdotdev/themes

standard/README.md
standard/cobalt_next.yaml
standard/previews/cobalt_next.yaml.svg

Theme/Cobalt Next

---

README.md

There is a tiny typo causing layout issues on the README, caused by an incorrectly-closed code block.
This PR fixes that and makes the readme more readable 👍

Fix typo that caused code block extension in README.md

---

standard/README.md
standard/monokai-pro_octagon.yml
standard/monokai_pro.yaml
standard/monokai_pro_classic.yaml
standard/monokai_pro_machine.yaml
standard/monokai_pro_ristretto.yml
standard/monokai_pro_spectrum.yml
standard/previews/monokai-pro_octagon.yml.svg
standard/previews/monokai_pro.yaml.svg
standard/previews/monokai_pro_classic.yaml.svg
standard/previews/monokai_pro_machine.yaml.svg
standard/previews/monokai_pro_ristretto.yml.svg
standard/previews/monokai_pro_spectrum.yml.svg

Borrows from unofficial monokai pro theme: (https://github.com/subtheme-dev/monokai-pro)
Sorry I don't know the what's the [official monokai pro theme](https://monokai.pro/) license, but it seems that borrow themes from other unofficial theme is ok.
If you think there is a risk to use such theme, feel free to let me know and I will close it.

add unofficial monokai pro themes

---

standard/fairyfloss.yaml
standard/jellybeans.yaml

i tried to regenerate the thumbnails but couldn't because of [this error](https://app.warp.dev/block/oYp2qk9k4pLW0thdFJu9uh), however, i hope everything else is satisfactory

ported fairyfloss and jellybeans

---

README.md
green_geeko.yaml
previews/green_geeko.yaml.svg

Green Geeko is my personal theme for VSCode and pretty much everything so I though I'd add it to Warp as well.

Added personal Green Geeko theme

---

README.md
catppuccin.yaml
previews/catppuccin.yaml.svg

According to discord user shares, I like the theme too:
the file follows this color palette: https://github.com/catppuccin/catppuccin and this style guide: https://github.com/catppuccin/style-guide

add catppuccin theme

---

README.md
lucario.yaml
previews/lucario.yaml.svg

Add [Lucario](https://github.com/raphamorim/lucario) theme.

Add Lucario theme

---

README.md
previews/simply_dark.yaml.svg
simply_dark.yaml

虚空巴达兽#8917
simply_dark
Ran the script for generating the thumbnails

simply dark theme

---

standard/github_dark_dimmed.yaml
standard/previews/github_dark_dimmed.yaml.svg

heymage#9743
GitHub Dark Dimmed
I tested the theme on my local machine.
Have you run the python script?
Yes 👍🏻

fix: update github dimmed theme

---

standard/README.md
standard/previews/vuesion.yaml.svg
standard/vuesion.yaml

scumethy#3063
Vuesion
Have your run the python script?
Yes

Add Vuesion theme

---

standard/README.md
standard/laser.yaml
standard/previews/laser.yaml.svg

Inspired on MiTo's Laser keycap set.
stz#0666
Laser
Have you run the python script?
Yes
Also tested locally.

Add Laser theme

---

standard/README.md
standard/panda_syntax.yaml
standard/previews/panda_syntax.yaml.svg

[Panda Syntax](https://github.com/PandaTheme)
- I tested it on my machine and still using it.
- Result of running `gen_theme_previews.py`

Add Panda Syntax theme

---

standard/README.md
standard/poimandres.yaml
standard/previews/poimandres.yaml.svg

`ubmit#1502`
Poimandres, which is a port of the [VS Code theme](https://github.com/drcmda/poimandres-theme)
Have you run the python script? `python3 ./scripts/gen_theme_previews.py <folder-name-eg-standard>` Yes
We cannot accept pull request that include custom background images because:
* of licensing restrictions
* we are trying to keep the binary size of the repo as small as possible (just the yaml files)
If your theme has an intended custom background image, include a comment in the yaml with a link to where people should download it.

feat: add poimandres theme

---

standard/README.md
standard/daobeam.yaml
standard/previews/daobeam.yaml.svg

If you're in our Discord server, we'd like to give you the Contributor Discord Role, pleaes include your username.
Note: It must be labelled like so: username#4747 (make sure to include the #XXXX).
daobeam
this theme has been my daily driver for ~3 months. Lots of docker/kubernetes usage, and numerous logging/scripting activities.
Have you run the python script? `python3 ./scripts/gen_theme_previews.py <folder-name-eg-standard>`
We cannot accept pull request that include custom background images because:
* of licensing restrictions
* we are trying to keep the binary size of the repo as small as possible (just the yaml files)
If your theme has an intended custom background image, include a comment in the yaml with a link to where people should download it.

Add daobeam theme

---

standard/README.md
standard/one_monokai.yaml
standard/previews/one_monokai.yaml.svg

Adam Ambrosius#5653
One Monokai
Yes, I generated the previews using the script.

Add theme one-monokai

---

standard/README.md
standard/previews/spaceduck.yaml.svg
standard/spaceduck.yaml

Spaceduck
I ran `python3 ./scripts/gen_theme_previews.py standard` to generate the preview.
Colors pulled from https://github.com/pineapplegiant/spaceduck-terminal#alacritty.

Add spaceduck theme

---

standard/README.md
standard/bilibili_dark.yaml
standard/previews/bilibili_dark.yaml.svg

Bilibili Dark
I ran python3 ./scripts/gen_theme_previews.py standard to generate the preview

feat: add bilibili dark theme

---

base16/README.md
base16/base16_asam.yaml
base16/previews/base16_asam.yaml.svg

Alan_Sealtiel#5729
Base16 Asam
With script `python3 ./scripts/gen_theme_previews.py base16`

feat: Add new theme Base16 Asam based in Base16 Pico

---

standard/kanagawa.yaml
standard/previews/kanagawa.yaml.svg

If you're in our Discord server, we'd like to give you the Contributor Discord Role, please include your username. Note: It must be labelled like so: username#4747 (make sure to include the #XXXX).
Kanagawa
Have you run the python script? `python3 ./scripts/gen_theme_previews.py <folder-name-eg-standard>`
Yes
We cannot accept pull request that include custom background images because:
- of licensing restrictions
- we are trying to keep the binary size of the repo as small as possible (just the yaml files)
If your theme has an intended custom background image, include a comment in the yaml with a link to where people should download it.

feat: Added Kanagawa theme

---

standard/README.md
standard/azuki.yaml
standard/previews/azuki.yaml.svg

Nothing
Azuki or azuki
`python3 ./scripts/gen_theme_previews.py <folder-name-eg-standard>`
We cannot accept pull request that include custom background images because:
- of licensing restrictions
- we are trying to keep the binary size of the repo as small as possible (just the yaml files)
If your theme has an intended custom background image, include a comment in the yaml with a link to where people should download it.

Add theme Azuki
